[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.nixpacks]
node = "22.12.0"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

[env]
NPM_CONFIG_PRODUCTION = "false"
