[build]
builder = "nixpacks"
[build.nixpacks]
node = "22.12.0"
[deploy]
startCommand = "npm install && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/health"
healthcheckTimeout = 30
[env]
NPM_CONFIG_PRODUCTION = "false"
