import { useState, useEffect } from "react";
  import { Card, CardContent } from "@/components/ui/card";
  import { Button } from "@/components/ui/button";
  import { Badge } from "@/components/ui/badge";
  import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
  import { FileText, Download, BarChart2, Users, AlertTriangle, TrendingUp, Clock, RefreshCw, Copy, CheckCircle } from "lucide-react";
  import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from "recharts";

  type ReportType = "server-health"|"staff-performance"|"disciplinary"|"activity";
  type Period = "7d"|"30d"|"90d";

  const REPORT_TYPES = [
    { id: "server-health",      label: "Server Health",      icon: <BarChart2 className="w-4 h-4" />,   desc: "Overall server health metrics and trends" },
    { id: "staff-performance",  label: "Staff Performance",  icon: <TrendingUp className="w-4 h-4" />,  desc: "Individual and team performance analysis" },
    { id: "disciplinary",       label: "Disciplinary",       icon: <AlertTriangle className="w-4 h-4" />,desc: "Strikes, warnings, and disciplinary actions" },
    { id: "activity",           label: "Activity Summary",   icon: <Clock className="w-4 h-4" />,       desc: "Activity logs and engagement statistics" },
  ] as const;

  export default function SmartReportsPage({ guildId }: { guildId: string }) {
    const [reportType, setReportType] = useState<ReportType>("server-health");
    const [period, setPeriod] = useState<Period>("30d");
    const [data, setData] = useState<any>(null);
    const [loading, setLoading] = useState(false);
    const [generated, setGenerated] = useState(false);
    const [copied, setCopied] = useState(false);

    async function generateReport() {
      setLoading(true); setGenerated(false);
      try {
        const [statsRes, strikesRes, loaRes, warningsRes, leaderboardRes] = await Promise.all([
          fetch(`/api/guilds/${guildId}/stats`, { credentials: "include" }),
          fetch(`/api/guilds/${guildId}/strikes`, { credentials: "include" }),
          fetch(`/api/guilds/${guildId}/loa`, { credentials: "include" }),
          fetch(`/api/guilds/${guildId}/warnings`, { credentials: "include" }),
          fetch(`/api/guilds/${guildId}/activity/leaderboard`, { credentials: "include" }),
        ]);
        const stats = statsRes.ok ? await statsRes.json() : {};
        const strikes = strikesRes.ok ? await strikesRes.json() : [];
        const loas = loaRes.ok ? await loaRes.json() : [];
        const warnings = warningsRes.ok ? await warningsRes.json() : [];
        const leaderboard = leaderboardRes.ok ? await leaderboardRes.json() : [];

        const activeStrikes = (strikes as any[]).filter((s:any) => s.active).length;
        const pendingLoas = (loas as any[]).filter((l:any) => l.status === "pending").length;
        const activeWarnings = (warnings as any[]).filter((w:any) => w.active).length;

        // Mock trend data (in production, this would come from a time-series API)
        const days = period === "7d" ? 7 : period === "30d" ? 30 : 90;
        const trendData = Array.from({ length: Math.min(days, 14) }, (_, i) => ({
          day: `Day ${i+1}`,
          activity: Math.floor(Math.random() * 50 + 20),
          staff: Math.floor(stats.activeStaff || 3 + Math.random() * 2),
        }));

        setData({
          generated: new Date().toLocaleString(),
          period,
          reportType,
          stats,
          activeStrikes,
          pendingLoas,
          activeWarnings,
          strikes: (strikes as any[]).slice(0, 5),
          loas: (loas as any[]).slice(0, 5),
          leaderboard: (leaderboard as any[]).slice(0, 10),
          trendData,
        });
        setGenerated(true);
      } catch (e) { console.error(e); }
      finally { setLoading(false); }
    }

    function copyReport() {
      if (!data) return;
      const text = `ZENITH STAFF REPORT
  Type: ${REPORT_TYPES.find(r => r.id === data.reportType)?.label}
  Period: ${data.period === "7d" ? "Last 7 Days" : data.period === "30d" ? "Last 30 Days" : "Last 90 Days"}
  Generated: ${data.generated}

  KEY METRICS
  ━━━━━━━━━━━━━━━━━━━━━━
  Total Staff:        ${data.stats.totalStaff || 0}
  Active Staff:       ${data.stats.activeStaff || 0}
  Pending Apps:       ${data.stats.pendingApplications || 0}
  Active Strikes:     ${data.activeStrikes}
  Active Warnings:    ${data.activeWarnings}
  Pending LOAs:       ${data.pendingLoas}
  Avg Activity Score: ${data.stats.avgActivityScore || 0}

  TOP PERFORMERS
  ━━━━━━━━━━━━━━━━━━━━━━
  ${data.leaderboard.slice(0,5).map((e:any,i:number) => `${i+1}. ${e.username || "Unknown"} — ${e.score || 0} pts`).join("\n")}

  Generated by Zenith Staff Management`;
      navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
    }

    const selectedType = REPORT_TYPES.find(r => r.id === reportType);

    return (
      <div className="space-y-5">
        <div>
          <h1 className="text-2xl font-extrabold tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6" style={{ color: "#d4af37" }} /> Smart Reports
          </h1>
          <p className="text-muted-foreground text-sm mt-0.5">Generate comprehensive staff performance reports.</p>
        </div>

        {/* Report Config */}
        <Card className="bg-card border-border">
          <CardContent className="p-5">
            <h3 className="text-sm font-bold mb-4">Configure Report</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-5">
              <div>
                <label className="text-xs text-muted-foreground mb-1.5 block">Report Type</label>
                <div className="grid grid-cols-2 gap-2">
                  {REPORT_TYPES.map(r => (
                    <button key={r.id} onClick={() => setReportType(r.id as ReportType)}
                      className="flex items-center gap-2 p-2.5 rounded-lg border text-left text-xs transition-all"
                      style={reportType === r.id
                        ? { background: "rgba(212,175,55,.12)", borderColor: "rgba(212,175,55,.4)", color: "#d4af37" }
                        : { background: "transparent", borderColor: "rgba(255,255,255,.08)", color: "rgba(255,255,255,.6)" }}>
                      {r.icon} <span className="font-medium truncate">{r.label}</span>
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <label className="text-xs text-muted-foreground mb-1.5 block">Time Period</label>
                <div className="space-y-2">
                  {[["7d","Last 7 Days"],["30d","Last 30 Days"],["90d","Last 90 Days"]].map(([v,l]) => (
                    <button key={v} onClick={() => setPeriod(v as Period)}
                      className="w-full flex items-center gap-2 p-2.5 rounded-lg border text-left text-xs transition-all"
                      style={period === v
                        ? { background: "rgba(212,175,55,.12)", borderColor: "rgba(212,175,55,.4)", color: "#d4af37" }
                        : { background: "transparent", borderColor: "rgba(255,255,255,.08)", color: "rgba(255,255,255,.6)" }}>
                      <div className="w-3 h-3 rounded-full border flex items-center justify-center" style={{ borderColor: period === v ? "#d4af37" : "rgba(255,255,255,.3)" }}>
                        {period === v && <div className="w-1.5 h-1.5 rounded-full" style={{ background: "#d4af37" }} />}
                      </div>
                      {l}
                    </button>
                  ))}
                </div>
              </div>
            </div>
            <Button onClick={generateReport} disabled={loading} className="w-full gap-2" style={{ background: "rgba(212,175,55,.9)", color: "#000" }}>
              {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
              {loading ? "Generating..." : "Generate Report"}
            </Button>
          </CardContent>
        </Card>

        {/* Report Output */}
        {generated && data && (
          <>
            <div className="flex items-center justify-between">
              <div>
                <h3 className="font-bold">{selectedType?.label} Report</h3>
                <p className="text-xs text-muted-foreground">Generated {data.generated} · {period === "7d" ? "Last 7 Days" : period === "30d" ? "Last 30 Days" : "Last 90 Days"}</p>
              </div>
              <Button variant="outline" size="sm" onClick={copyReport} className="gap-2">
                {copied ? <CheckCircle className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied!" : "Copy Report"}
              </Button>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-3">
              {[
                { label: "Total Staff",    value: data.stats.totalStaff || 0,          color: "#3b82f6" },
                { label: "Active",         value: data.stats.activeStaff || 0,         color: "#22c55e" },
                { label: "Pending Apps",   value: data.stats.pendingApplications || 0, color: "#a855f7" },
                { label: "Strikes",        value: data.activeStrikes,                  color: "#ef4444" },
                { label: "Warnings",       value: data.activeWarnings,                 color: "#f97316" },
                { label: "On LOA",         value: data.stats.activeLoa || 0,           color: "#d4af37" },
              ].map(m => (
                <Card key={m.label} className="bg-card border-border">
                  <CardContent className="p-3 text-center">
                    <div className="text-2xl font-black" style={{ color: m.color }}>{m.value}</div>
                    <div className="text-[10px] text-muted-foreground mt-0.5 uppercase tracking-wider">{m.label}</div>
                  </CardContent>
                </Card>
              ))}
            </div>

            <Card className="bg-card border-border">
              <CardContent className="p-5">
                <h4 className="text-sm font-bold mb-4">Activity Trend</h4>
                <ResponsiveContainer width="100%" height={200}>
                  <LineChart data={data.trendData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.07)" />
                    <XAxis dataKey="day" tick={{ fontSize: 10, fill: "rgba(255,255,255,0.4)" }} />
                    <YAxis tick={{ fontSize: 10, fill: "rgba(255,255,255,0.4)" }} />
                    <Tooltip contentStyle={{ background: "#1a1d23", border: "1px solid rgba(255,255,255,.1)", borderRadius: "8px", fontSize: 11 }} />
                    <Line type="monotone" dataKey="activity" stroke="#d4af37" strokeWidth={2} dot={false} name="Activity" />
                  </LineChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {data.leaderboard.length > 0 && (
              <Card className="bg-card border-border">
                <CardContent className="p-5">
                  <h4 className="text-sm font-bold mb-3">Top Performers</h4>
                  <div className="space-y-2">
                    {data.leaderboard.slice(0,5).map((e: any, i: number) => (
                      <div key={i} className="flex items-center gap-3 py-2 border-b border-border last:border-0">
                        <span className="text-sm font-black w-6" style={{ color: i < 3 ? "#d4af37" : "rgba(255,255,255,.3)" }}>#{i+1}</span>
                        <span className="flex-1 text-sm truncate">{e.username || "Unknown"}</span>
                        <span className="text-sm font-bold">{(e.score || 0).toLocaleString()} pts</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </>
        )}
      </div>
    );
  }
  